# 服务器配置
server:
  port: 8080  # 网关服务端口

# Spring配置
spring:
  application:
    name: gateway  # 服务名称
  cloud:
    nacos:
      # Nacos服务发现配置
      discovery:
        server-addr: localhost:8848  # Nacos服务器地址
      # Nacos配置中心配置
      config:
        server-addr: localhost:8848  # Nacos服务器地址
        file-extension: yaml  # 配置文件格式
    gateway:
      discovery:
        locator:
          enabled: true  # 启用服务发现
      # 路由配置
      routes:
        # 用户服务路由
        - id: user-service
          uri: lb://user-service  # 负载均衡到用户服务
          predicates:
            - Path=/api/user/**  # 匹配路径
          filters:
            - StripPrefix=2  # 去除路径前缀
        
        # 论文服务路由
        - id: paper-service
          uri: lb://paper-service  # 负载均衡到论文服务
          predicates:
            - Path=/api/paper/**  # 匹配路径
          filters:
            - StripPrefix=2  # 去除路径前缀
        
        # 评审服务路由
        - id: review-service
          uri: lb://review-service  # 负载均衡到评审服务
          predicates:
            - Path=/api/review/**  # 匹配路径
          filters:
            - StripPrefix=2  # 去除路径前缀

# 跨域配置
cors:
  allowedOrigins: "*"  # 允许的来源
  allowedMethods: "*"  # 允许的HTTP方法
  allowedHeaders: "*"  # 允许的请求头
  allowCredentials: true  # 允许携带认证信息
  maxAge: 3600  # 预检请求有效期（秒） 