server:
  port: 8081

spring:
  application:
    name: paper-service
  datasource:
    url: jdbc:postgresql://localhost:5432/paper_review
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ 